import equilipy.variables as var

def read_dict(db):
    try: 
        var.nElementsCS = db['nElementsCS']
        var.nSpeciesCS = db['nSpeciesCS']
        var.nSolnPhasesSysCS = db['nSolnPhasesSysCS']
        var.nCountSublatticeCS = db['nCountSublatticeCS']
        var.nMaxSpeciesPhaseCS = db['nMaxSpeciesPhaseCS']
        var.nParamCS = db['nParamCS']
        var.nMagParamCS = db['nMagParamCS']
        var.nMaxSublatticeCS = db['nMaxSublatticeCS']
        var.nSolnPhasesSysMax = db['nSolnPhasesSysMax']
        var.nGibbsCoeff = db['nGibbsCoeff']
        var.nMaxGibbsEqs = db['nMaxGibbsEqs']
        var.nParamMax = db['nParamMax']
        var.iPhaseCS = db['iPhaseCS']
        var.iParticlesPerMoleCS = db['iParticlesPerMoleCS']
        var.iPhaseSublatticeCS = db['iPhaseSublatticeCS']
        var.nGibbsEqSpecies = db['nGibbsEqSpecies']
        var.nSublatticePhaseCS = db['nSublatticePhaseCS']
        var.nParamPhaseCS = db['nParamPhaseCS']
        var.nSpeciesPhaseCS = db['nSpeciesPhaseCS']
        var.nMagParamPhaseCS = db['nMagParamPhaseCS']
        var.dAtomicMass = db['dAtomicMass']
        var.cRegularParamCS = db['cRegularParamCS']
        var.cElementNameCS = db['cElementNameCS']
        var.cSolnPhaseTypeCS = db['cSolnPhaseTypeCS']
        var.cSolnPhaseNameCS = db['cSolnPhaseNameCS']
        var.cSpeciesNameCS = db['cSpeciesNameCS']
        var.nPairsSROCS = db['nPairsSROCS']
        var.nConstituentSublatticeCS = db['nConstituentSublatticeCS']
        var.nSublatticeElementsCS = db['nSublatticeElementsCS']
        var.dGibbsMagneticCS = db['dGibbsMagneticCS']
        var.dStoichSublatticeCS = db['dStoichSublatticeCS']
        var.dZetaSpeciesCS = db['dZetaSpeciesCS']
        var.dGibbsCoeffSpeciesTemp = db['dGibbsCoeffSpeciesTemp']
        var.dStoichSpeciesCS = db['dStoichSpeciesCS']
        var.iMagneticParamCS = db['iMagneticParamCS']
        var.dMagneticParamCS = db['dMagneticParamCS']
        var.iRegularParamCS = db['iRegularParamCS']
        var.dRegularParamCS = db['dRegularParamCS']
        var.cPairNameCS = db['cPairNameCS']
        var.iConstituentSublatticeCS = db['iConstituentSublatticeCS']
        var.iPairIDCS = db['iPairIDCS']
        var.iChemicalGroupCS = db['iChemicalGroupCS']
        var.dSublatticeChargeCS = db['dSublatticeChargeCS']
        var.dStoichPairsCS = db['dStoichPairsCS']
        var.dConstituentCoefficientsCS = db['dConstituentCoefficientsCS']
        var.dCoordinationNumberCS = db['dCoordinationNumberCS']
        var.cConstituentNameSUBCS = db['cConstituentNameSUBCS']
        var.cPhaseNames= db['cPhaseNames']
        var.nPureSpeciesCS = db['nPureSpeciesCS']
        var.nSolnPhaseCS = db['nSolnPhaseCS']
        var.indx = db['indx']
        var.INFO = db['INFO']
        var.DataBase = db['DataBase']
        var.iCounterGibbsEqn = db['iCounterGibbsEqn']
        var.cPeriodicTable = db['cPeriodicTable']
    except: TypeError
    
    
    return None