title: Equilipy
description: A python package for calculating chemical equilibria using CALPHAD approach
remote_theme: just-the-docs
url: https://ornl.github.io/equilipy/
baseurl: "/docs"
permalink: pretty

aux_links:
  Template Repository: https://github.com/ORNL/Equilipy